apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wyx7ia254-go
  janus-idp.io/tekton: wyx7ia254-go
  backstage.io/kubernetes-id: wyx7ia254-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wyx7ia254-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
