apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wyx7ia254-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wyx7ia254-go 
  name: wyx7ia254-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: wyx7ia254-go 
